from django.core.management.base import BaseCommand
from Egresados.apps.home.models import Egresados

def insert_data():
	Egresados(nombres = 'Andrea Julieth', apellidos = 'Labrador Sanchez', numero_documento = '0', promocion = '2002', telefono = '3118516381', direccion = 'Transv. 9 #44C - 69 B/Portachuelo', correo_electronico = 'andrks@live.com', ultimos_estudios = 'Especialidad Derecho Laboral y Seguridad', lugar_ultimo_estudio = 'Universidad Libre').save()
	Egresados(nombres = 'Silvia Juliana', apellidos = 'Palma Sotelo', numero_documento = '1001093490', promocion = '2018', telefono = '3163099019', direccion = 'Cll 32 12-78 B/centenario', correo_electronico = 'Palmajuliana7@gmail.com', ultimos_estudios = 'Técnico en sistemas', lugar_ultimo_estudio = 'Sena').save()
	Egresados(nombres = 'Lina Maria', apellidos = 'Rojas Orjuela', numero_documento = '1007600149', promocion = '2018', telefono = '3224300208', direccion = 'Mz 12 C 3 B/Altos del peñon', correo_electronico = 'linamariarojas175@gmail.com', ultimos_estudios = 'Bachiller', lugar_ultimo_estudio = 'CESMA').save()
	Egresados(nombres = 'Laura Valentina', apellidos = 'Lòpez Gonzàlez', numero_documento = '1007356027', promocion = '2018', telefono = '3163494286', direccion = 'Brisas agua blanca Apart 607 torre C', correo_electronico = 'valenlogo@hotmail.com', ultimos_estudios = 'Bachiller', lugar_ultimo_estudio = 'CESMA').save()
	Egresados(nombres = 'Vanessa Alexandra', apellidos = 'Bojacà Carrillo', numero_documento = '1003568463', promocion = '2018', telefono = '3053201839', direccion = 'Mz 18 Cs 15 B/Primero de Enero', correo_electronico = 'vanetureina0523@gmail.com', ultimos_estudios = 'Bachiller', lugar_ultimo_estudio = 'CESMA').save()
	Egresados(nombres = 'Marìa Paula', apellidos = 'Barrero Sierra', numero_documento = '1005754962', promocion = '2018', telefono = '3219572252', direccion = 'Cll 45A #9-73 B/Portachuelo', correo_electronico = 'mariabarrero0809@gmail.com', ultimos_estudios = 'Bachiller', lugar_ultimo_estudio = 'CESMA').save()
	Egresados(nombres = 'Juliàn Humberto', apellidos = 'Rojas Molina', numero_documento = '1000288691', promocion = '2018', telefono = '3143083840', direccion = 'Cll 34 #5-70 B/San Jorge', correo_electronico = 'Chavjulian@hotmail.com', ultimos_estudios = 'Bachiller', lugar_ultimo_estudio = 'CESMA').save()
	Egresados(nombres = 'Carlos Andrès', apellidos = 'Ramirez Vanegas', numero_documento = '1003555051', promocion = '2018', telefono = '3104850338', direccion = 'Transv 9 #44b-207 B/Portachuelo', correo_electronico = 'Calichevanegas674@gmail.com', ultimos_estudios = 'Bachiller', lugar_ultimo_estudio = 'CESMA').save()
	Egresados(nombres = 'Laura Sofia', apellidos = 'Parga Garcia', numero_documento = '1003556205', promocion = '2018', telefono = '3157758665', direccion = 'Mz 73 Cs 2 B/Kennedy', correo_electronico = 'pargalaurasofia@gmail.com', ultimos_estudios = 'Bachiller', lugar_ultimo_estudio = 'CESMA').save()
	Egresados(nombres = 'Isis Sofia', apellidos = 'Rodrìguez Nieto', numero_documento = '1003634622', promocion = '2018', telefono = '3177175057', direccion = 'Mz 7 Cs 4 Algarrobos IV etapa', correo_electronico = 'isissofiaro2015@gmail.com', ultimos_estudios = 'Bachiller', lugar_ultimo_estudio = 'CESMA').save()
	Egresados(nombres = 'Estefania', apellidos = 'Labrador Sànchez', numero_documento = '1007782129', promocion = '2018', telefono = '3138729126', direccion = 'Transv 9 #44c 69 B/Portachuelo', correo_electronico = 'stefy.labrador.sanchez@gmail.com', ultimos_estudios = 'Técnico en sistemas', lugar_ultimo_estudio = 'Sena').save()
	Egresados(nombres = 'Fabiàn Manuel', apellidos = 'Gil Camacho', numero_documento = '1003516299', promocion = '2018', telefono = '3016833835', direccion = 'Cll 11 #24-120 Cs 37 Conjunto La Fontana', correo_electronico = 'fabiangil452@gmail.com', ultimos_estudios = 'Técnico en sistemas', lugar_ultimo_estudio = 'Sena').save()
	Egresados(nombres = 'Lizeth Geraldine', apellidos = 'Acosta Duràn', numero_documento = '1003556329', promocion = '2018', telefono = '3193697238', direccion = 'Cll 32B #4-50 B/San Jorge', correo_electronico = 'lizeethcitaacosta@gmail.com', ultimos_estudios = 'Técnico en sistemas', lugar_ultimo_estudio = 'Sena').save()
	Egresados(nombres = 'Brandon Emir', apellidos = 'Ardila Rodrìguez', numero_documento = '1000137328', promocion = '2017', telefono = '3213950942', direccion = 'Mz 12 Cs 1 Vivisol 2', correo_electronico = 'brandonardila4@gmail.com', ultimos_estudios = 'Técnico en sistemas', lugar_ultimo_estudio = 'Sena').save()
	Egresados(nombres = 'María Alejandra', apellidos = 'González Gómez', numero_documento = '1005820435', promocion = '2018', telefono = '3219242269', direccion = 'Alicante 1 Cs A Mz 23', correo_electronico = 'gomezmaria0925@gmail.com', ultimos_estudios = 'Tecnico en sistemas', lugar_ultimo_estudio = 'SENA').save()
	Egresados(nombres = 'Yulian Lorenzo', apellidos = 'Castillo Calderón', numero_documento = '1003634695', promocion = '2018', telefono = '3132094214', direccion = 'Mz 70 Casa 1 B/ Kennedy', correo_electronico = 'yulianlocotfm10@gmail.com', ultimos_estudios = 'Tecnico en Sistemas', lugar_ultimo_estudio = 'SENA').save()
	Egresados(nombres = 'David Andrès', apellidos = 'Bustamante Arteaga', numero_documento = '1000456122', promocion = '2018', telefono = '3212764844', direccion = 'Cto. Condado San Luis Cs 22', correo_electronico = 'holasoydavid324@gmail.com', ultimos_estudios = 'Técnico en sistemas', lugar_ultimo_estudio = 'Sena').save()

class Command(BaseCommand):
	def handle(self, **options):
		insert_data()