# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egresados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('promocion', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=40)),
                ('correo_electronico', models.CharField(max_length=40)),
                ('ultimos_estudios', models.CharField(max_length=40)),
                ('lugar_ultimo_estudio', models.CharField(max_length=80)),
            ],
        ),
    ]
