# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-19 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresados',
            name='numero_documento',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
